In [1]:
import torch


tt = torch.tensor([
  [1, 2],
  [3, 4],
  [5, 6],
])

# Shape returns dimensions of tensor
A, B = tt.shape

# View transposes the tensor according to the given dimensions
tt.view(B, A)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [2]:
tt = torch.tensor([
  [
    [1, 2],
    [3, 4],
    [5, 6],
  ],
  [
    [7, 8],
    [9, 10],
    [11, 12],
  ],
])

A, B, C = tt.shape

# View args must multiply to the same number as original dimensions
assert(A * B * C == 2 * 3 * 2)

# So far as that is true, original tensor can be reshaped
tt.view(3, 4)
tt.view(2, 6)

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

In [36]:
import torch

t = torch.tensor([
  [
    [1, 2],
    [3, 4],
    [5, 6],
  ],
  [
    [7, 8],
    [9, 10],
    [11, 12],
  ],
])

# This will reshape the tensor as well
# : - keep as is
# N - pick dimension N
t[:, -1, :]
t[:, :, :]
t[:, 2]

t[1]
t[1, 1]
t[1, 1, 1]
t[0, 0, 0]

# Comparing tensort
# yields comparison of underlying data
t[0, :, 1] == t[0][:, 1]
t[0] == t[0]

tensor([[True, True],
        [True, True],
        [True, True]])

In [62]:
import torch
from torch.nn import functional as F

t = torch.tensor([1, 2, 3, 1, 2, 4], dtype=torch.float32)

# Softmax normalizes the tensor between 0..1
# and makes sure that sum of all elements is 1
w = F.softmax(t, dim=0).tolist()

print(f'Logits:\n{t}')
print(f'Weights:\n{w}')
print(f'Sum:\n{sum(w)}')
print('---')

Logits:
tensor([1., 2., 3., 1., 2., 4.])
Weights:
[0.0286441370844841, 0.07786283642053604, 0.21165314316749573, 0.0286441370844841, 0.07786283642053604, 0.5753328800201416]
Sum:
0.9999999701976776
---
